openapi: 3.0.1
info:
  title: CronJobAPI
  description: API Definition of CronJobAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/cron
paths:
  /:
    get:
      responses:
        default:
          description: Default response
